### ISSUE TITLE
Name and logo

### ISSUE THREAD

**Issue by alfonsogarciacaro** [alfonsogarciacaro/Fable#10]
Though I already got used to it, "Fabel" was just a code name until releasing the project (which is not happening quite yet) and the plan was to decide a new name with the community. So that's what this issue is for, together with a request for someone with better design skills than me (mine are close to zero) to propose a logo... if possible not a square with F# logo on upper left, please ;)

Waiting for your wonderful proposals, in the meanwhile, some pros and cons about current candidates:

- FABEL: **pro**, may drag on Babel.js appeal among the (huge) JS community; **con** (by @cloudroutine), F# projects should have names that stand on their own that aren't bound to a heritage in projects from other languages, like how Fix just changed its name to Forge. It gives the impression that they're their own entities, unconstrained by the expectations of copying the decisions and designs of their forebearers and frees them to pursue their own distinct form and destiny.
- FABLE: like above but without the cons.
- FABELOUS: Maybe? ;)
- Something with "-SCRIPT": **cons**, there are already F# scripts and also could give the impression it's a different language, when they're exactly the same (albeit small semantic differences).

**Comment by Krzysztof-Cieslak** [comment]
Fable :+1:, Fabel is :neutral_face:, rest :-1:

**Comment by cloudRoutine** [comment]
Fable :+1:

**Comment by rodrigovidal** [comment]
Fable :+1:

**Comment by nelak** [comment]
Fable :+1:

**Comment by alfonsogarciacaro** [comment]
If we don't get many votes for another candidate it looks like we have a clear winner :+1: Probably the best timing to make the name change will be when moving the repo to fsprojects.

**Comment by davidtme** [comment]
Fable :+1:

**Comment by alfonsogarciacaro** [comment]
Name has been changed :) I'll probably open another issue after moving to fsprojects for the logo
